### PR TITLE
Fix instability resulting from +seed commandline use.

### PR DESCRIPTION
**Pull request by joshuascheid**
Still under test.

### CODE REVIEW

**Comment by paul-donahue** [comment]
This breaks the cardinal rule of sknobs: No comments allowed. :smile:

I think that this is equivalent to changing https://github.com/jayantom/sknobs/blob/master/src/c/sknobs.c#L752 to just NOP.

I notice that `SEED=4 command +seed=5` uses seed of 5 in the current and proposed code but if `+seed=5` is specified in foo.knobs and we do `SEED=4 command -f foo.knobs` then we use the seed of 4.  There's no way around that latter case since it could've been `-f a,b,c` and so you don't know which file (and therefore which seed) to use until you randomly pick a file.  So I'm not proposing a change to that behavior.  However, in the latter case, I think that the `sknobs_get_value("seed", 0)` will return 5 even if the seed actually being used is 4 since this PR will prevent subsequent setting of the actual seed but not of the "seed" knob.

**Comment by joshuascheid** [comment]
> I think that this is equivalent to changing https://github.com/jayantom/sknobs/blob/master/src/c/sknobs.c#L752 to just NOP.

That might "solve" the current problem.  But doesn't prevent multiple direct calls to sknobs_set_seed() in user code.

> 
> I notice that `SEED=4 command +seed=5` uses seed of 5 in the current and proposed code but if `+seed=5` is specified in foo.knobs and we do `SEED=4 command -f foo.knobs` then we use the seed of 4. There's no way around that latter case since it could've been `-f a,b,c` and so you don't know which file (and therefore which seed) to use until you randomly pick a file. So I'm not proposing a change to that behavior. However, in the latter case, I think that the `sknobs_get_value("seed", 0)` will return 5 even if the seed actually being used is 4 since this PR will prevent subsequent setting of the actual seed but not of the "seed" knob.

I think the fix for this is to change https://github.com/jayantom/sknobs/blob/master/src/c/sknobs.c#L753 to add an `else`.  Agree?

**Comment by joshuascheid** [comment]
New commits address https://github.com/jayantom/sknobs/pull/9#issuecomment-699156002

**Comment by paul-donahue** [comment]
> That might "solve" the current problem. But doesn't prevent multiple direct calls to sknobs_set_seed() in user code.

True.

> I think the fix for this is to change https://github.com/jayantom/sknobs/blob/master/src/c/sknobs.c#L753 to add an `else`. Agree?

Yes.  Turn the `if` to `else if`.

**Comment by paul-donahue** [comment]
I've either forgotten how to give a thumbs up to a PR on github or I'm not privileged enough to do so in this repo (though I can comment).

I approve.

**Comment by joshuascheid** [comment]
Kudos to @vdhotre-ventana for debugging this.

**Pull request merged**
